# Generated by Django 3.0.7 on 2020-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20201028_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prom_id',
            field=models.CharField(max_length=50, verbose_name='Prom ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prom_token',
            field=models.CharField(max_length=50, verbose_name='Prom token'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_token',
            field=models.CharField(max_length=50, verbose_name='Telegram Token'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viber_token',
            field=models.CharField(max_length=50, verbose_name='Viber Token'),
        ),
    ]
