# Generated by Django 3.0.7 on 2020-10-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20201028_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prom_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prom_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='viber_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='viber_token',
        ),
    ]
