# Generated by Django 3.0.7 on 2020-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20201028_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prom_id',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Prom ID'),
        ),
    ]
