# Generated by Django 3.0.7 on 2020-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_profile_prom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prom_token',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Prom token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_active',
            field=models.BooleanField(default=False, verbose_name='Telegram on/off'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_token',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Telegram Token'),
        ),
        migrations.AddField(
            model_name='profile',
            name='viber_active',
            field=models.BooleanField(default=False, verbose_name='Viber on/off'),
        ),
        migrations.AddField(
            model_name='profile',
            name='viber_token',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Viber Token'),
        ),
    ]
