# Generated by Django 3.0.7 on 2020-11-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20201104_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='услуга')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'СМС уведомление',
                'verbose_name_plural': 'СМС уведомления',
            },
        ),
    ]
