# Generated by Django 3.0.7 on 2020-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_auto_20201106_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsstatus',
            name='created',
        ),
        migrations.RemoveField(
            model_name='smsstatus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='smsstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='smsstatus',
            name='updated',
        ),
        migrations.AddField(
            model_name='smsstatus',
            name='sms_1',
            field=models.BooleanField(default=False, verbose_name='Принятие заказа Вашей компанией'),
        ),
        migrations.AddField(
            model_name='smsstatus',
            name='sms_2',
            field=models.BooleanField(default=False, verbose_name='Номер Вашей карты и заказа, если клиент выбрал оплату картой (Поле для ввода номера карты)'),
        ),
        migrations.AddField(
            model_name='smsstatus',
            name='sms_3',
            field=models.BooleanField(default=False, verbose_name='Отправлять номер ТТН смской автоматически после создания (поле для ввода ключа апи НП и поле для ввода ключа Джастин)'),
        ),
        migrations.AddField(
            model_name='smsstatus',
            name='sms_4',
            field=models.BooleanField(default=False, verbose_name='Отправлять смс с ссылкой для добавления отзыва Вашей компании после 2 недель после отправки'),
        ),
    ]
