# Generated by Django 3.0.7 on 2020-11-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20201106_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsstatus',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Смс рассылка'),
        ),
    ]
