# Generated by Django 3.0.7 on 2020-11-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_smsstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsstatus',
            name='profile',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Profile', verbose_name='профиль'),
        ),
    ]
