# Generated by Django 3.1.3 on 2020-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20201117_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, verbose_name='Role'),
        ),
    ]
