# Generated by Django 3.1.3 on 2020-11-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20201119_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Payment Plan')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.paymentplan'),
        ),
    ]
