# Generated by Django 3.1.3 on 2020-11-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20201125_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_plan',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.paymentplan', verbose_name='Payment Plan'),
        ),
    ]
