# Generated by Django 3.1.3 on 2020-11-27 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_auto_20201125_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(14)),
        ),
    ]
