# Generated by Django 3.1.3 on 2020-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_paymentplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_end',
            field=models.DateTimeField(default=None),
        ),
    ]
