# Generated by Django 3.1.3 on 2020-11-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_auto_20201127_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_end',
        ),
    ]
