# Generated by Django 3.1.3 on 2020-11-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0033_profile_payment_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_end',
        ),
    ]
