# Generated by Django 3.1.4 on 2021-01-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_profile_payment_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='магазин')),
                ('url', models.URLField(null=True, verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True)),
                ('shop_token', models.CharField(default=None, max_length=50, null=True, verbose_name='токен магазина')),
                ('number_of_orders', models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='кол-во заказов')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='shop',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.shop', verbose_name='Магазин'),
        ),
    ]
