# Generated by Django 3.1.4 on 2021-01-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0036_auto_20210106_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shop',
        ),
        migrations.AddField(
            model_name='profile',
            name='shop',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='clients.Shop', verbose_name='Магазин'),
        ),
    ]
