# Generated by Django 3.1.4 on 2021-01-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0037_auto_20210109_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shop',
            field=models.ManyToManyField(blank=True, default=None, to='clients.Shop', verbose_name='Магазин'),
        ),
    ]
