# Generated by Django 3.1.4 on 2021-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0038_auto_20210109_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Activation code'),
        ),
    ]
