# Generated by Django 3.0.7 on 2020-11-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='имя'),
        ),
    ]
