# Generated by Django 3.0.7 on 2020-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20201104_1524'),
        ('order', '0002_productinorder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='магазин')),
                ('url', models.URLField(verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Shop', verbose_name='магазин'),
        ),
    ]
