# Generated by Django 3.1.3 on 2020-12-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201130_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_lastname',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_secondname',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='отчество'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='prom_id',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='вид платежа'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='имя'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
