# Generated by Django 3.1.3 on 2020-12-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201202_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='номер тел'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='магазин'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(null=True, verbose_name='ссылка'),
        ),
    ]
