# Generated by Django 3.1.3 on 2020-12-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_profile_payment_end'),
        ('order', '0006_auto_20201202_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.profile', verbose_name='профиль'),
        ),
    ]
