# Generated by Django 3.1.3 on 2020-12-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20201204_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.shop', verbose_name='магазин'),
        ),
    ]
