# Generated by Django 3.1.3 on 2020-12-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_lastname',
            field=models.CharField(default=None, max_length=53, null=True, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=52, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_secondname',
            field=models.CharField(default=None, max_length=54, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default=None, max_length=56, null=True, verbose_name='способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=None, max_length=55, null=True, verbose_name='вид платежа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='prom_id',
            field=models.CharField(default=None, max_length=51, null=True, verbose_name='id'),
        ),
    ]
