# Generated by Django 3.1.4 on 2021-01-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0035_profile_payment_end'),
        ('order', '0012_auto_20201205_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='profile',
        ),
        migrations.AddField(
            model_name='shop',
            name='profile',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='clients.Profile', verbose_name='профиль'),
        ),
    ]
